;
; File generated by cc65 v 2.19 - Git 52e438792
;
	.fopt		compiler,"cc65 v 2.19 - Git 52e438792"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_puts
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$48,$65,$6C,$6C,$6F,$2C,$20,$77,$6F,$72,$6C,$64,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _puts
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

