
import { CpuType } from './cpu-interface';

export enum Opcode {
    BRK_imp = 0x00,
    ORA_izx = 0x01,
    ORA_zp = 0x05,
    ASL_zp = 0x06,
    PHP_imp = 0x08,
    ORA_imm = 0x09,
    ASL_acc = 0x0A,
    ORA_abs = 0x0D,
    ASL_abs = 0x0E,
    BPL_rel = 0x10,
    ORA_izy = 0x11,
    ORA_zpx = 0x15,
    ASL_zpx = 0x16,
    CLC_imp = 0x18,
    ORA_aby = 0x19,
    ORA_abx = 0x1D,
    ASL_abx = 0x1E,
    JSR_abs = 0x20,
    AND_izx = 0x21,
    BIT_zp = 0x24,
    AND_zp = 0x25,
    ROL_zp = 0x26,
    PLP_imp = 0x28,
    AND_imm = 0x29,
    ROL_acc = 0x2A,
    BIT_abs = 0x2C,
    AND_abs = 0x2D,
    ROL_abs = 0x2E,
    BMI_rel = 0x30,
    AND_izy = 0x31,
    AND_zpx = 0x35,
    ROL_zpx = 0x36,
    SEC_imp = 0x38,
    AND_aby = 0x39,
    AND_abx = 0x3D,
    ROL_abx = 0x3E,
    RTI_imp = 0x40,
    EOR_izx = 0x41,
    EOR_zp = 0x45,
    LSR_zp = 0x46,
    PHA_imp = 0x48,
    EOR_imm = 0x49,
    LSR_acc = 0x4A,
    JMP_abs = 0x4C,
    EOR_abs = 0x4D,
    LSR_abs = 0x4E,
    BVC_rel = 0x50,
    EOR_izy = 0x51,
    EOR_zpx = 0x55,
    LSR_zpx = 0x56,
    CLI_imp = 0x58,
    EOR_aby = 0x59,
    EOR_abx = 0x5D,
    LSR_abx = 0x5E,
    RTS_imp = 0x60,
    ADC_izx = 0x61,
    ADC_zp = 0x65,
    ROR_zp = 0x66,
    PLA_imp = 0x68,
    ADC_imm = 0x69,
    ROR_acc = 0x6A,
    JMP_ind = 0x6C,
    ADC_abs = 0x6D,
    ROR_abs = 0x6E,
    BVS_rel = 0x70,
    ADC_izy = 0x71,
    ADC_zpx = 0x75,
    ROR_zpx = 0x76,
    SEI_imp = 0x78,
    ADC_aby = 0x79,
    ADC_abx = 0x7D,
    ROR_abx = 0x7E,
    STA_izx = 0x81,
    STY_zp = 0x84,
    STA_zp = 0x85,
    STX_zp = 0x86,
    DEY_imp = 0x88,
    TXA_imp = 0x8A,
    STY_abs = 0x8C,
    STA_abs = 0x8D,
    STX_abs = 0x8E,
    BCC_rel = 0x90,
    STA_izy = 0x91,
    STY_zpx = 0x94,
    STA_zpx = 0x95,
    STX_zpy = 0x96,
    TYA_imp = 0x98,
    STA_aby = 0x99,
    TXS_imp = 0x9A,
    STA_abx = 0x9D,
    LDY_imm = 0xA0,
    LDA_izx = 0xA1,
    LDX_imm = 0xA2,
    LDY_zp = 0xA4,
    LDA_zp = 0xA5,
    LDX_zp = 0xA6,
    TAY_imp = 0xA8,
    LDA_imm = 0xA9,
    TAX_imp = 0xAA,
    LDY_abs = 0xAC,
    LDA_abs = 0xAD,
    LDX_abs = 0xAE,
    BCS_rel = 0xB0,
    LDA_izy = 0xB1,
    LDY_zpx = 0xB4,
    LDA_zpx = 0xB5,
    LDX_zpy = 0xB6,
    CLV_imp = 0xB8,
    LDA_aby = 0xB9,
    TSX_imp = 0xBA,
    LDY_abx = 0xBC,
    LDA_abx = 0xBD,
    LDX_aby = 0xBE,
    CPY_imm = 0xC0,
    CMP_izx = 0xC1,
    CPY_zp = 0xC4,
    CMP_zp = 0xC5,
    DEC_zp = 0xC6,
    INY_imp = 0xC8,
    CMP_imm = 0xC9,
    DEX_imp = 0xCA,
    CPY_abs = 0xCC,
    CMP_abs = 0xCD,
    DEC_abs = 0xCE,
    BNE_rel = 0xD0,
    CMP_izy = 0xD1,
    CMP_zpx = 0xD5,
    DEC_zpx = 0xD6,
    CLD_imp = 0xD8,
    CMP_aby = 0xD9,
    CMP_abx = 0xDD,
    DEC_abx = 0xDE,
    CPX_imm = 0xE0,
    SBC_izx = 0xE1,
    CPX_zp = 0xE4,
    SBC_zp = 0xE5,
    INC_zp = 0xE6,
    INX_imp = 0xE8,
    SBC_imm = 0xE9,
    NOP_imp = 0xEA,
    CPX_abs = 0xEC,
    SBC_abs = 0xED,
    INC_abs = 0xEE,
    BEQ_rel = 0xF0,
    SBC_izy = 0xF1,
    SBC_zpx = 0xF5,
    INC_zpx = 0xF6,
    SED_imp = 0xF8,
    SBC_aby = 0xF9,
    SBC_abx = 0xFD,
    INC_abx = 0xFE,

    // 65C02 Extensions
    TSB_zp = 0x04,
    TSB_abs = 0x0C,
    ORA_izp = 0x12,
    TRB_zp = 0x14,
    INC_acc = 0x1A,
    TRB_abs = 0x1C,
    AND_izp = 0x32,
    BIT_zpx = 0x34,
    DEC_acc = 0x3A,
    BIT_abx = 0x3C,
    EOR_izp = 0x52,
    PHY_imp = 0x5A,
    STZ_zp = 0x64,
    ADC_izp = 0x72,
    STZ_zpx = 0x74,
    PLY_imp = 0x7A,
    JMP_iax = 0x7C,
    BRA_rel = 0x80,
    BIT_imm = 0x89,
    STA_izp = 0x92,
    STZ_abs = 0x9C,
    STZ_abx = 0x9E,
    LDA_izp = 0xB2,
    CMP_izp = 0xD2,
    PHX_imp = 0xDA,
    SBC_izp = 0xF2,
    PLX_imp = 0xFA,
}

export interface OpcodeInfo {
    name: string;
    mode: 'imp' | 'acc' | 'imm' | 'zp' | 'zpx' | 'zpy' | 'abs' | 'abx' | 'aby' | 'ind' | 'izx' | 'izy' | 'rel' | 'iax' | 'izp' | 'ptr'; // ptr added for some internal flexibility if needed, otherwise stick to standard
    cycles: number;
    cpu?: CpuType;
    pageBoundCycles?: number; // Extra cycles if page boundary crossed
    branchTakenCycles?: number; // Extra cycles if branch taken
}

export const OPCODES: Record<number, OpcodeInfo> = {
    [Opcode.BRK_imp]: { name: 'BRK', mode: 'imp', cycles: 7 },
    [Opcode.ORA_izx]: { name: 'ORA', mode: 'izx', cycles: 6 },
    [Opcode.ORA_zp]: { name: 'ORA', mode: 'zp', cycles: 3 },
    [Opcode.ASL_zp]: { name: 'ASL', mode: 'zp', cycles: 5 },
    [Opcode.PHP_imp]: { name: 'PHP', mode: 'imp', cycles: 3 },
    [Opcode.ORA_imm]: { name: 'ORA', mode: 'imm', cycles: 2 },
    [Opcode.ASL_acc]: { name: 'ASL', mode: 'acc', cycles: 2 },
    [Opcode.ORA_abs]: { name: 'ORA', mode: 'abs', cycles: 4 },
    [Opcode.ASL_abs]: { name: 'ASL', mode: 'abs', cycles: 6 },
    [Opcode.BPL_rel]: { name: 'BPL', mode: 'rel', cycles: 2, branchTakenCycles: 1, pageBoundCycles: 2 },
    [Opcode.ORA_izy]: { name: 'ORA', mode: 'izy', cycles: 5, pageBoundCycles: 1 },
    [Opcode.ORA_zpx]: { name: 'ORA', mode: 'zpx', cycles: 4 },
    [Opcode.ASL_zpx]: { name: 'ASL', mode: 'zpx', cycles: 6 },
    [Opcode.CLC_imp]: { name: 'CLC', mode: 'imp', cycles: 2 },
    [Opcode.ORA_aby]: { name: 'ORA', mode: 'aby', cycles: 4, pageBoundCycles: 1 },
    [Opcode.ORA_abx]: { name: 'ORA', mode: 'abx', cycles: 4, pageBoundCycles: 1 },
    [Opcode.ASL_abx]: { name: 'ASL', mode: 'abx', cycles: 7 },
    [Opcode.JSR_abs]: { name: 'JSR', mode: 'abs', cycles: 6 },
    [Opcode.AND_izx]: { name: 'AND', mode: 'izx', cycles: 6 },
    [Opcode.BIT_zp]: { name: 'BIT', mode: 'zp', cycles: 3 },
    [Opcode.AND_zp]: { name: 'AND', mode: 'zp', cycles: 3 },
    [Opcode.ROL_zp]: { name: 'ROL', mode: 'zp', cycles: 5 },
    [Opcode.PLP_imp]: { name: 'PLP', mode: 'imp', cycles: 4 },
    [Opcode.AND_imm]: { name: 'AND', mode: 'imm', cycles: 2 },
    [Opcode.ROL_acc]: { name: 'ROL', mode: 'acc', cycles: 2 },
    [Opcode.BIT_abs]: { name: 'BIT', mode: 'abs', cycles: 4 },
    [Opcode.AND_abs]: { name: 'AND', mode: 'abs', cycles: 4 },
    [Opcode.ROL_abs]: { name: 'ROL', mode: 'abs', cycles: 6 },
    [Opcode.BMI_rel]: { name: 'BMI', mode: 'rel', cycles: 2, branchTakenCycles: 1, pageBoundCycles: 2 },
    [Opcode.AND_izy]: { name: 'AND', mode: 'izy', cycles: 5, pageBoundCycles: 1 },
    [Opcode.AND_zpx]: { name: 'AND', mode: 'zpx', cycles: 4 },
    [Opcode.ROL_zpx]: { name: 'ROL', mode: 'zpx', cycles: 6 },
    [Opcode.SEC_imp]: { name: 'SEC', mode: 'imp', cycles: 2 },
    [Opcode.AND_aby]: { name: 'AND', mode: 'aby', cycles: 4, pageBoundCycles: 1 },
    [Opcode.AND_abx]: { name: 'AND', mode: 'abx', cycles: 4, pageBoundCycles: 1 },
    [Opcode.ROL_abx]: { name: 'ROL', mode: 'abx', cycles: 7 },
    [Opcode.RTI_imp]: { name: 'RTI', mode: 'imp', cycles: 6 },
    [Opcode.EOR_izx]: { name: 'EOR', mode: 'izx', cycles: 6 },
    [Opcode.EOR_zp]: { name: 'EOR', mode: 'zp', cycles: 3 },
    [Opcode.LSR_zp]: { name: 'LSR', mode: 'zp', cycles: 5 },
    [Opcode.PHA_imp]: { name: 'PHA', mode: 'imp', cycles: 3 },
    [Opcode.EOR_imm]: { name: 'EOR', mode: 'imm', cycles: 2 },
    [Opcode.LSR_acc]: { name: 'LSR', mode: 'acc', cycles: 2 },
    [Opcode.JMP_abs]: { name: 'JMP', mode: 'abs', cycles: 3 },
    [Opcode.EOR_abs]: { name: 'EOR', mode: 'abs', cycles: 4 },
    [Opcode.LSR_abs]: { name: 'LSR', mode: 'abs', cycles: 6 },
    [Opcode.BVC_rel]: { name: 'BVC', mode: 'rel', cycles: 2, branchTakenCycles: 1, pageBoundCycles: 2 },
    [Opcode.EOR_izy]: { name: 'EOR', mode: 'izy', cycles: 5, pageBoundCycles: 1 },
    [Opcode.EOR_zpx]: { name: 'EOR', mode: 'zpx', cycles: 4 },
    [Opcode.LSR_zpx]: { name: 'LSR', mode: 'zpx', cycles: 6 },
    [Opcode.CLI_imp]: { name: 'CLI', mode: 'imp', cycles: 2 },
    [Opcode.EOR_aby]: { name: 'EOR', mode: 'aby', cycles: 4, pageBoundCycles: 1 },
    [Opcode.EOR_abx]: { name: 'EOR', mode: 'abx', cycles: 4, pageBoundCycles: 1 },
    [Opcode.LSR_abx]: { name: 'LSR', mode: 'abx', cycles: 7 },
    [Opcode.RTS_imp]: { name: 'RTS', mode: 'imp', cycles: 6 },
    [Opcode.ADC_izx]: { name: 'ADC', mode: 'izx', cycles: 6 },
    [Opcode.ADC_zp]: { name: 'ADC', mode: 'zp', cycles: 3 },
    [Opcode.ROR_zp]: { name: 'ROR', mode: 'zp', cycles: 5 },
    [Opcode.PLA_imp]: { name: 'PLA', mode: 'imp', cycles: 4 },
    [Opcode.ADC_imm]: { name: 'ADC', mode: 'imm', cycles: 2 },
    [Opcode.ROR_acc]: { name: 'ROR', mode: 'acc', cycles: 2 },
    [Opcode.JMP_ind]: { name: 'JMP', mode: 'ind', cycles: 5 },
    [Opcode.ADC_abs]: { name: 'ADC', mode: 'abs', cycles: 4 },
    [Opcode.ROR_abs]: { name: 'ROR', mode: 'abs', cycles: 6 },
    [Opcode.BVS_rel]: { name: 'BVS', mode: 'rel', cycles: 2, branchTakenCycles: 1, pageBoundCycles: 2 },
    [Opcode.ADC_izy]: { name: 'ADC', mode: 'izy', cycles: 5, pageBoundCycles: 1 },
    [Opcode.ADC_zpx]: { name: 'ADC', mode: 'zpx', cycles: 4 },
    [Opcode.ROR_zpx]: { name: 'ROR', mode: 'zpx', cycles: 6 },
    [Opcode.SEI_imp]: { name: 'SEI', mode: 'imp', cycles: 2 },
    [Opcode.ADC_aby]: { name: 'ADC', mode: 'aby', cycles: 4, pageBoundCycles: 1 },
    [Opcode.ADC_abx]: { name: 'ADC', mode: 'abx', cycles: 4, pageBoundCycles: 1 },
    [Opcode.ROR_abx]: { name: 'ROR', mode: 'abx', cycles: 7 },
    [Opcode.STA_izx]: { name: 'STA', mode: 'izx', cycles: 6 },
    [Opcode.STY_zp]: { name: 'STY', mode: 'zp', cycles: 3 },
    [Opcode.STA_zp]: { name: 'STA', mode: 'zp', cycles: 3 },
    [Opcode.STX_zp]: { name: 'STX', mode: 'zp', cycles: 3 },
    [Opcode.DEY_imp]: { name: 'DEY', mode: 'imp', cycles: 2 },
    [Opcode.TXA_imp]: { name: 'TXA', mode: 'imp', cycles: 2 },
    [Opcode.STY_abs]: { name: 'STY', mode: 'abs', cycles: 4 },
    [Opcode.STA_abs]: { name: 'STA', mode: 'abs', cycles: 4 },
    [Opcode.STX_abs]: { name: 'STX', mode: 'abs', cycles: 4 },
    [Opcode.BCC_rel]: { name: 'BCC', mode: 'rel', cycles: 2, branchTakenCycles: 1, pageBoundCycles: 2 },
    [Opcode.STA_izy]: { name: 'STA', mode: 'izy', cycles: 6 },
    [Opcode.STY_zpx]: { name: 'STY', mode: 'zpx', cycles: 4 },
    [Opcode.STA_zpx]: { name: 'STA', mode: 'zpx', cycles: 4 },
    [Opcode.STX_zpy]: { name: 'STX', mode: 'zpy', cycles: 4 },
    [Opcode.TYA_imp]: { name: 'TYA', mode: 'imp', cycles: 2 },
    [Opcode.STA_aby]: { name: 'STA', mode: 'aby', cycles: 5 }, // STA abs,y is 5, not 4+1? Stores never take extra cycle?
    [Opcode.TXS_imp]: { name: 'TXS', mode: 'imp', cycles: 2 },
    [Opcode.STA_abx]: { name: 'STA', mode: 'abx', cycles: 5 },
    [Opcode.LDY_imm]: { name: 'LDY', mode: 'imm', cycles: 2 },
    [Opcode.LDA_izx]: { name: 'LDA', mode: 'izx', cycles: 6 },
    [Opcode.LDX_imm]: { name: 'LDX', mode: 'imm', cycles: 2 },
    [Opcode.LDY_zp]: { name: 'LDY', mode: 'zp', cycles: 3 },
    [Opcode.LDA_zp]: { name: 'LDA', mode: 'zp', cycles: 3 },
    [Opcode.LDX_zp]: { name: 'LDX', mode: 'zp', cycles: 3 },
    [Opcode.TAY_imp]: { name: 'TAY', mode: 'imp', cycles: 2 },
    [Opcode.LDA_imm]: { name: 'LDA', mode: 'imm', cycles: 2 },
    [Opcode.TAX_imp]: { name: 'TAX', mode: 'imp', cycles: 2 },
    [Opcode.LDY_abs]: { name: 'LDY', mode: 'abs', cycles: 4 },
    [Opcode.LDA_abs]: { name: 'LDA', mode: 'abs', cycles: 4 },
    [Opcode.LDX_abs]: { name: 'LDX', mode: 'abs', cycles: 4 },
    [Opcode.BCS_rel]: { name: 'BCS', mode: 'rel', cycles: 2, branchTakenCycles: 1, pageBoundCycles: 2 },
    [Opcode.LDA_izy]: { name: 'LDA', mode: 'izy', cycles: 5, pageBoundCycles: 1 },
    [Opcode.LDY_zpx]: { name: 'LDY', mode: 'zpx', cycles: 4 },
    [Opcode.LDA_zpx]: { name: 'LDA', mode: 'zpx', cycles: 4 },
    [Opcode.LDX_zpy]: { name: 'LDX', mode: 'zpy', cycles: 4 },
    [Opcode.CLV_imp]: { name: 'CLV', mode: 'imp', cycles: 2 },
    [Opcode.LDA_aby]: { name: 'LDA', mode: 'aby', cycles: 4, pageBoundCycles: 1 },
    [Opcode.TSX_imp]: { name: 'TSX', mode: 'imp', cycles: 2 },
    [Opcode.LDY_abx]: { name: 'LDY', mode: 'abx', cycles: 4, pageBoundCycles: 1 },
    [Opcode.LDA_abx]: { name: 'LDA', mode: 'abx', cycles: 4, pageBoundCycles: 1 },
    [Opcode.LDX_aby]: { name: 'LDX', mode: 'aby', cycles: 4, pageBoundCycles: 1 },
    [Opcode.CPY_imm]: { name: 'CPY', mode: 'imm', cycles: 2 },
    [Opcode.CMP_izx]: { name: 'CMP', mode: 'izx', cycles: 6 },
    [Opcode.CPY_zp]: { name: 'CPY', mode: 'zp', cycles: 3 },
    [Opcode.CMP_zp]: { name: 'CMP', mode: 'zp', cycles: 3 },
    [Opcode.DEC_zp]: { name: 'DEC', mode: 'zp', cycles: 5 },
    [Opcode.INY_imp]: { name: 'INY', mode: 'imp', cycles: 2 },
    [Opcode.CMP_imm]: { name: 'CMP', mode: 'imm', cycles: 2 },
    [Opcode.DEX_imp]: { name: 'DEX', mode: 'imp', cycles: 2 },
    [Opcode.CPY_abs]: { name: 'CPY', mode: 'abs', cycles: 4 },
    [Opcode.CMP_abs]: { name: 'CMP', mode: 'abs', cycles: 4 },
    [Opcode.DEC_abs]: { name: 'DEC', mode: 'abs', cycles: 6 },
    [Opcode.BNE_rel]: { name: 'BNE', mode: 'rel', cycles: 2, branchTakenCycles: 1, pageBoundCycles: 2 },
    [Opcode.CMP_izy]: { name: 'CMP', mode: 'izy', cycles: 5, pageBoundCycles: 1 },
    [Opcode.CMP_zpx]: { name: 'CMP', mode: 'zpx', cycles: 4 },
    [Opcode.DEC_zpx]: { name: 'DEC', mode: 'zpx', cycles: 6 },
    [Opcode.CLD_imp]: { name: 'CLD', mode: 'imp', cycles: 2 },
    [Opcode.CMP_aby]: { name: 'CMP', mode: 'aby', cycles: 4, pageBoundCycles: 1 },
    [Opcode.CMP_abx]: { name: 'CMP', mode: 'abx', cycles: 4, pageBoundCycles: 1 },
    [Opcode.DEC_abx]: { name: 'DEC', mode: 'abx', cycles: 7 },
    [Opcode.CPX_imm]: { name: 'CPX', mode: 'imm', cycles: 2 },
    [Opcode.SBC_izx]: { name: 'SBC', mode: 'izx', cycles: 6 },
    [Opcode.CPX_zp]: { name: 'CPX', mode: 'zp', cycles: 3 },
    [Opcode.SBC_zp]: { name: 'SBC', mode: 'zp', cycles: 3 },
    [Opcode.INC_zp]: { name: 'INC', mode: 'zp', cycles: 5 },
    [Opcode.INX_imp]: { name: 'INX', mode: 'imp', cycles: 2 },
    [Opcode.SBC_imm]: { name: 'SBC', mode: 'imm', cycles: 2 },
    [Opcode.NOP_imp]: { name: 'NOP', mode: 'imp', cycles: 2 },
    [Opcode.CPX_abs]: { name: 'CPX', mode: 'abs', cycles: 4 },
    [Opcode.SBC_abs]: { name: 'SBC', mode: 'abs', cycles: 4 },
    [Opcode.INC_abs]: { name: 'INC', mode: 'abs', cycles: 6 },
    [Opcode.BEQ_rel]: { name: 'BEQ', mode: 'rel', cycles: 2, branchTakenCycles: 1, pageBoundCycles: 2 },
    [Opcode.SBC_izy]: { name: 'SBC', mode: 'izy', cycles: 5, pageBoundCycles: 1 },
    [Opcode.SBC_zpx]: { name: 'SBC', mode: 'zpx', cycles: 4 },
    [Opcode.INC_zpx]: { name: 'INC', mode: 'zpx', cycles: 6 },
    [Opcode.SED_imp]: { name: 'SED', mode: 'imp', cycles: 2 },
    [Opcode.SBC_aby]: { name: 'SBC', mode: 'aby', cycles: 4, pageBoundCycles: 1 },
    [Opcode.SBC_abx]: { name: 'SBC', mode: 'abx', cycles: 4, pageBoundCycles: 1 },
    [Opcode.INC_abx]: { name: 'INC', mode: 'abx', cycles: 7 },

    // 65C02
    [Opcode.TSB_zp]: { name: 'TSB', mode: 'zp', cycles: 5, cpu: '65C02' },
    [Opcode.TSB_abs]: { name: 'TSB', mode: 'abs', cycles: 6, cpu: '65C02' },
    [Opcode.ORA_izp]: { name: 'ORA', mode: 'izp', cycles: 5, cpu: '65C02' },
    [Opcode.TRB_zp]: { name: 'TRB', mode: 'zp', cycles: 5, cpu: '65C02' },
    [Opcode.INC_acc]: { name: 'INC', mode: 'acc', cycles: 2, cpu: '65C02' },
    [Opcode.TRB_abs]: { name: 'TRB', mode: 'abs', cycles: 6, cpu: '65C02' },
    [Opcode.AND_izp]: { name: 'AND', mode: 'izp', cycles: 5, cpu: '65C02' },
    [Opcode.BIT_zpx]: { name: 'BIT', mode: 'zpx', cycles: 4, cpu: '65C02' },
    [Opcode.DEC_acc]: { name: 'DEC', mode: 'acc', cycles: 2, cpu: '65C02' },
    [Opcode.BIT_abx]: { name: 'BIT', mode: 'abx', cycles: 4, cpu: '65C02' },
    [Opcode.EOR_izp]: { name: 'EOR', mode: 'izp', cycles: 5, cpu: '65C02' },
    [Opcode.PHY_imp]: { name: 'PHY', mode: 'imp', cycles: 3, cpu: '65C02' },
    [Opcode.STZ_zp]: { name: 'STZ', mode: 'zp', cycles: 3, cpu: '65C02' },
    [Opcode.ADC_izp]: { name: 'ADC', mode: 'izp', cycles: 5, cpu: '65C02' },
    [Opcode.STZ_zpx]: { name: 'STZ', mode: 'zpx', cycles: 4, cpu: '65C02' },
    [Opcode.PLY_imp]: { name: 'PLY', mode: 'imp', cycles: 4, cpu: '65C02' },
    [Opcode.JMP_iax]: { name: 'JMP', mode: 'iax', cycles: 6, cpu: '65C02' },
    [Opcode.BRA_rel]: { name: 'BRA', mode: 'rel', cycles: 2, branchTakenCycles: 1, pageBoundCycles: 1, cpu: '65C02' }, // BRA is 3 if taken
    [Opcode.BIT_imm]: { name: 'BIT', mode: 'imm', cycles: 2, cpu: '65C02' },
    [Opcode.STA_izp]: { name: 'STA', mode: 'izp', cycles: 5, cpu: '65C02' },
    [Opcode.STZ_abs]: { name: 'STZ', mode: 'abs', cycles: 4, cpu: '65C02' },
    [Opcode.STZ_abx]: { name: 'STZ', mode: 'abx', cycles: 5, cpu: '65C02' },
    [Opcode.LDA_izp]: { name: 'LDA', mode: 'izp', cycles: 5, cpu: '65C02' },
    [Opcode.CMP_izp]: { name: 'CMP', mode: 'izp', cycles: 5, cpu: '65C02' },
    [Opcode.PHX_imp]: { name: 'PHX', mode: 'imp', cycles: 3, cpu: '65C02' },
    [Opcode.SBC_izp]: { name: 'SBC', mode: 'izp', cycles: 5, cpu: '65C02' },
    [Opcode.PLX_imp]: { name: 'PLX', mode: 'imp', cycles: 4, cpu: '65C02' },
};
